### ISSUE TITLE
サインアップ直後に投稿しようとすると、エラーになりました。

### ISSUE THREAD

**Issue by hogehiga** [kyan-syoya/n_b_b#23]
こんにちは。サインアップ直後に投稿しようとすると、エラーになりましたので確認をお願いしたいです。

# 概要
サインアップ直後に投稿しようとすると、エラーになる

# 再現手順
1. d2877f6f07ef2e7f3f98d01ba5ecaacf24a11959 を取得する(現段階のdevelopブランチの最新)
1. 新しいユーザーを登録できる状態にする(例えば、```bundle exec rake db:migrate:reset```)
1. ```rails s```でアプリを起動する
1. Firefoxで新規プロファイルを作成し、/にアクセスする
1. 「会員登録」をクリックする
1. ユーザ名「test」「男」メールアドレス「test@example.com」パスワードおよびパスワード確認「password」と入力し、「会員登録」ボタンをクリックする。
1. 「新規投稿する」をクリックする
1. titleに「テスト」、contentに「テスト2」と入力し、「投稿ボタン」をクリックする

# 期待される結果
投稿一覧画面へ遷移し、title「テスト」、content「テスト2」の投稿が表示される。

# 実際の結果
ブラウザに以下のメッセージを伴うエラー画面が表示される

```
NoMethodError in PostsController#create
undefined method `id' for nil:NilClass
Extracted source (around line #14):

12    @post = Post.new(title: params[:title],
13                     content: params[:content],
14                     user_id: @current_user.id)
15    if @post.save
16      redirect_to("/")
17    else
```

よろしくお願いします。

**Comment by puremoru** [comment]
ご指摘していただきありがとうございます。修正に努めます。

**Comment by irish15** [comment]
解決しました！
